### ISSUE TITLE
How to build plex-operator?

### ISSUE THREAD

**Issue by djerfy** [mcadam/plex-operator#2]
Hi @mcadam,

I tested to build `plex-operator` but in failure, I always fall on this error (example):

```text
$ go build -o build/_output/bin/plex-operator
[...]
go: finding k8s.io/metrics v0.0.0
go: k8s.io/metrics@v0.0.0: unknown revision v0.0.0
go get: error loading module requirements
```

But same problem with `k8s.io/cloud-provider`, `k8s.io/kube-controller-manager`... Return unknown revision v0.0.0

An command/option that I forget?

Thanks

**Comment by djerfy** [comment]
The last error is solved, now I have:

```text
can't load package: package github.com/mcadam/plex-operator: build constraints exclude all Go files in ...
```

My environment:

```bash
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/djerfy/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/usr/local/Go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.9/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hb/97vym9y96w5ct559byxpr2k00000gn/T/go-build766640600=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by mcadam** [comment]
Hi, the plex-operator is built using the operator-sdk, I am building it using the sdk commands.
There might not be a way around it with classic go commands directly, I recommend you read over there https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md

I run that command to build it and push it:

`operator-sdk build mcadm/plex-operator:v0.0.1`
